Import setup from setuptools instead of distutils.core
ros-visualization/rqt_launch pull request #25
Opened 2023-02-26 10:34 UTC by arne48

Recently users of newer distributions who build Noetic from source noticed issues when importing setup from distutils.core.
This problem was discussed on [Discourse](https://discourse.ros.org/t/ros-1-and-python-3-10s-deprecation-of-distutils-core/29834), and we hope that we can make the needed updates to Noetic to allow for future builds from source of Noetic.
As a first step, this PR introduces changes from the [Noetic Migration Guide](https://wiki.ros.org/noetic/Migration#Setuptools_instead_of_Distutils) that addresses the change to the setuptools module instead of distutils.core and the corresponding buildtool_depend tags for python 2&3.

2023-02-26 12:57 UTC, MatthijsBurgh approved these changes

2023-02-26 12:58 UTC, MatthijsBurgh requested changes
Missing dependsl on setuptools

2023-02-26 13:03 UTC, arne48 commented
@MatthijsBurgh yes unfortunately this package is not format version 3 yet so I reverted the addition for this PR.
But I can create a new PR that migrated the package.xml to version 3.
I just thought doing both in this PR would be a bit convoluted.

2023-02-26 13:06 UTC, arne48 commented
Currently the following rqt_plugins still are not migrated to format version 3:
- rqt
- rqt_action
- rqt_image_view
- rqt_launch
- rqt_srv

2023-02-26 16:31 UTC, MatthijsBurgh commented
@arne48 I think it totally fine to migrate it to package format 3. As it is required for the required migration to setuptools.

2023-02-27 23:24 UTC, arne48 commented
@MatthijsBurgh not all packages did also the buildtool_depend addition to the package.xml when they switched to setuptools.
But I agree that it should be completely following the migration guide.
So I will amend the PRs for:
- rqt
- rqt_action
- rqt_image_view
- rqt_launch
- rqt_srv

To include the migration of the package.xml to format version 3.

2023-03-01 02:02 UTC, arne48 commented
I amended the PR for:

- rqt
- rqt_action
- rqt_image_view
- rqt_launch
- rqt_srv

with the update for format version 3 of the package.xml

2023-03-01 09:37 UTC, MatthijsBurgh approved these changes

2023-03-01 15:27 UTC, 130s approved these changes

2023-03-01 22:52 UTC, merged